core/urls.py
from django.urls import path
from core import views
from .views import *

app_name = "core" 

urlpatterns = [
    path('', views.Home, name='home'),
    path('submit/', views.SubmitDataframe.as_view(), name='submitdataframe'),
    path('view/', views.ViewDatas, name='viewdatas'),
    path('manipulate/<id>/', views.Manipulate, name='manipulate'),
    path('ajax/savedataframe', views.Ajax_SaveDataFrame, name='savedataframe'),
]

webpandas/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User
from .validators import validate_file_extension, valid_extensions
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class DataFrame(models.Model):
    """
    This holds the model for dataframe
    """
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=500, help_text='Name of the file ')
    dataframe = models.FileField(upload_to='core/', help_text=valid_extensions() ,validators=[validate_file_extension])
    


    def __str__(self):
        return str(self.name)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    creation_date = models.DateField(auto_now_add=True)
    email_confirmed = models.BooleanField(default=False)

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

core/forms.py
from django import forms
from django.core.files.base import File
from django.db.models import query
from django.db.models.expressions import Col
from django.db.models.fields import BLANK_CHOICE_DASH
from django.forms import widgets
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column, Button, Submit, HTML, Field
from django.core.exceptions import ValidationError
from .validators import validate_file_extension, valid_extensions
import re
import datetime
import pytz


class UploadDataFrameForm(forms.ModelForm):

    dataframe = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': False}), required=True)
    
    
    class Meta:
        model = DataFrame
        fields = '__all__'
        widgets = {
            'creator': forms.HiddenInput()
        }

    def __init__(self, *args, **kwargs):
        creator = kwargs.pop('creator')
        super(UploadDataFrameForm, self).__init__(*args, **kwargs)
        self.fields['dataframe'].help_text = valid_extensions()
        self.helper = FormHelper(self)
        self.fields['creator'].initial = creator
        self.helper.layout = Layout(
            'creator',
            Row(
                Column('name'),
            ),
            Row(
                Column('dataframe')
            ),
            Submit('submit', 'Submit'),
        )


class SignUpForm(UserCreationForm):
    creation_date = forms.DateField()
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username','creation_date','password1','password2')

core/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.http.response import HttpResponse, Http404
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.forms import UserCreationForm
from django.utils import datastructures
from django.views.generic import UpdateView, CreateView, ListView, DetailView
from django.shortcuts import render, redirect
from core.models import *
from core.forms import *
from django.http import HttpResponseRedirect
from django.urls import reverse
import json
import os
import pandas as pd

# Create your views here.

def Home(request):
    '''
    This is the home page
    '''
    context = {
        '':'',
    }
    return render(request, 'core/home.html', context)


class SubmitDataframe(CreateView):
    '''
    Form for submitting dataframes
    '''
    model = DataFrame
    form_class = UploadDataFrameForm
    template_name = 'core/submitdataframe.html'


    def get_form_kwargs(self):
        kwargs = super(SubmitDataframe, self).get_form_kwargs()
        kwargs.update({'creator':self.request.user.id})
        return kwargs

    def form_invalid(self, form):
        return HttpResponseRedirect(reverse('core:submitdataframe'))

    def form_valid(self, form):
        print(form)
        form = form.cleaned_data
        DataFrame.objects.create(creator=form['creator'], name=form['name'], dataframe=form['dataframe'])
        return HttpResponseRedirect(reverse('core:submitdataframe'))

def ViewDatas(request):
    '''
    This is to view all the dataframes owned by the user
    '''
    dataframes = DataFrame.objects.filter(creator=request.user.id).exclude(dataframe__exact='')
    baddataframes = len(DataFrame.objects.filter(creator=request.user.id).filter(dataframe__exact=''))
    
    alerts = []

    if baddataframes != 0:
        alerts.append({'alerttype':'alert-danger','message':f'You have {baddataframes} bad data frames'})


    context = {
        'dataframes':dataframes,
        'baddataframes':baddataframes,
        'alerts':alerts,
    }
    return render(request, 'core/viewdatas.html', context) 


def Manipulate(request, id):
    '''
    This is the editing page
    '''
    obj = DataFrame.objects.filter(pk=id).first()
    df_web = obj.dataframe
    df = pd.read_csv(df_web)
    df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
    
    # output = df.to_html(index=None)


    output = clean_df(df)

    context = {
        'output':output,
    }
    return render(request, 'core/manipulate.html', context)



def Ajax_SaveDataFrame(request):
    '''
    Passes dataframe back to panda to save it
    '''
    
    
    path = 'media/core/temp/'+str(request.user.id)+'/outputs/'
    isExist = os.path.exists(path)

    if not isExist:
        os.makedirs(path)

    data = json.loads(request.GET['string'])
    df = pd.DataFrame.from_dict(data)
    df.columns = df.iloc[0]
    df = df[1:]
    df.to_csv(path+'output.csv')
    pathid = request.GET['pathname'].split('/')[-2]



    obj = DataFrame.objects.filter(pk=pathid).first()
    obj.dataframe = 'core/temp/'+str(request.user.id)+'/outputs/output.csv'
    obj.save()
    print(obj, obj.dataframe)
    
    
    return HttpResponse("Success!") # Sending an success response




def clean_df(df):
    '''
    Function to clean the dataframes submitting in SubmitDataFrame
    '''
    # print(df)
    html = df.to_html(index=True)
    columns = len(df.columns)+1
    html = re.sub('border="1" ',"",html)
    html = re.sub('class="dataframe"', 'class="dataframe table table-bordered"', html)
    html = re.sub('<tr style="text-align: right;">','<tr>', html)


    return html

core/templates/core/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

core/templates/core/home.html
{% extends 'base.html' %}

core/templates/core/manipulate.html
{% extends 'base.html' %}



{% block title %}
<title>download dataframes</title>
{% endblock %}

{% block pagetitle %}
View your dataframes
{% endblock %}



{% block content %}

{% autoescape off %}

<div class="col">

    <button type="button" class="btn btn-primary" id='savebtn'>
        <a>Save Table</a>
    </button>
    {{output}}
</div>


{% endautoescape %}




<script>

    $(document).ready(function() {
        let thcount = document.querySelectorAll('thead th');
        $(thcount).each(function(index) {
            $(`<th class="justify-content-between" data-col-index=`+index+`>
                    <div class="d-flex justify-content-around">
                        <button type="button" class="btn btn-primary findandreplace" title="Find and Replace">
                            <i class="material-icons">
                                find_replace
                            </i>
                        </button>
                    
                        <button type="button" class="btn btn-danger deletecol" title="Delete Column">
                            <i class="material-icons">
                                delete
                            </i>
                        </button>
                    </div>
            </th>`).insertBefore('table > thead > tr:first');
        });

        const table = document.querySelector("table");
        let secondColumnELements = getColumnElementsByIndexColumn(table, 1);
        labelHeaders();

    $('.findandreplace').click(function(){
        let find = prompt('What do you want to find');
        let replace = prompt('What do you want to replace it with');
        
        let indexColumn = $(this)
            .parent().attr('data-col-index');
        let data = getColumnElementsByIndexColumn(table, indexColumn);
            $.each(data.slice(1), function(i){
                string = data[i].textContent;
                string2 = string.replaceAll(find,replace);
                data[i].textContent = string2
            });
        });

    

    $('.deletecol').click(function(){
        let indexColumn = $(this)
            .parent().attr('data-col-index');
        let data = getColumnElementsByIndexColumn(table, indexColumn);
            $.each(data, function(i){
                data[i].remove()
            });
    });

    function labelHeaders() {
        let c = document.querySelectorAll('thead tr th');
        if ( c ) {
            for (i = 0; i < c.length; i++){
                c[i].setAttribute('data-col-index',i); // Used to refer to it in pandas data
            }
        }
    }

    /**
    * 
    * @param {Object} table: the table dom selector 
    * @param {indexColumn} number: start count with 0 
    * @returns Array with the column element selected by index column
    */
    function getColumnElementsByIndexColumn(table, indexColumn) {
        const tableRows = table.querySelectorAll("tr");
        let columnElements = [];

        for (row of tableRows) {
            let columnElement = row.children[indexColumn];
            columnElements.push(columnElement);
        }

        return columnElements;
    }
    
    $('#savebtn').click(function(){
        

        let datas = Object.create(null);
        thcount = document.querySelectorAll('table thead tr th');
        $(thcount).each(function(index){
            
            let data = getColumnElementsByIndexColumn(table, index);
                subdatas = []
                $.each(data, function(i){
                    // console.log(data[i].textContent)
                    subdatas.push(data[i].textContent)
                    
                })
            datas[index]=subdatas
            // datas.push([index,subdatas])
        });
        // string = JSON.stringify(datas);
        console.log(datas)
        console.log(JSON.stringify(datas))
            $.ajax({
                url: "{% url 'core:savedataframe' %}",
                data:{
                    'string': JSON.stringify(datas),
                    'pathname': window.location.href
                },
                success: function(){
                    alert('gucci')
                }
            });
        });                
    });
                
</script>
                
{% endblock %}

core/templates/core/submitdataframe.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
<title>crispy</title>
{% endblock %}

{% block pagetitle %}
Submit your dataframe
{% endblock %}



{% block content %}

<div class='container'>
    <div class='pb-5'>
            {% crispy form %}
    </div>
</div>

{% endblock %}

core/templates/core/viewdatas.html
{% extends 'base.html' %}



{% block title %}
<title>download dataframes</title>
{% endblock %}

{% block alerts %}

    {% for alert in alerts %}
        <div class="alert {{alert.alerttype}}" role="alert">
            {{alert.message}}
        </div>
    {% endfor %}

{% endblock %}

{% block pagetitle %}
View your dataframes
{% endblock %}


{% block content %}




{% for frame in dataframes %}

    <div class="card">  
        <div class="card-header">
            {{frame.name}}
        </div>
        <div class="card-body">
            <a class="btn btn-primary" href="{{frame.dataframe.url}}" role="button">Download</a>
            <a class="btn btn-primary" href="{% url 'core:manipulate' id=frame.id %}" role="button">Manipulate Data</a>
        </div>
    </div>

{% endfor %}

{% endblock %}