core/urls.py
from django.urls import path
from core import views
from .views import *

app_name = "core" 

urlpatterns = [
    path('', views.Home, name='home'),
    path('submit/', views.SubmitDataframe.as_view(), name='submitdataframe'),
    path('view/', views.ViewDatas, name='viewdatas'),
    path('manipulate/<id>/', views.Manipulate, name='manipulate'),
    path('ajax/savedataframe', views.Ajax_SaveDataFrame, name='savedataframe'),
]

webpandas/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webpandas/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
    <script src="{% static 'js/iconify.js' %}" type="text/javascript"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/stackoverflowicons.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block title %}
    {% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
      <div class="collapse navbar-collapse" >
        <a class="navbar-brand" href="{% url 'core:home' %}">
          <span class="iconify" data-icon="mdi:panda" style="color:white;" data-width="48", data-height="48"></span>
          Web Pandas
        </a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class='nav-item active'>
            <a class ='nav-link' href="{% url 'core:home' %}">Home </a>
          </li>
          
          <li>
            <div class="btn-group">
              <a href="{% url 'core:viewdatas' %}"><button type="button" class="btn btn-secondary">Data Frames</button></a>
              <button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="sr-only">Toggle Dropdown</span>
              </button>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'core:submitdataframe' %}">Submit New Data Frame</a>
                <div class="dropdown-divider"></div>
                {% for frame in dataframes %}
                <a class="dropdown-item" href="{% url 'core:manipulate' id=frame.id %}">{{frame}}</a>
                {% endfor %}
              </div>
            </div>
          </li>

        </ul>
      </div>

    </nav>
      {% block alerts %}
      {% endblock %}
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-8">
          <h1 class="mt-2">
              {% block pagetitle %}
              {% endblock %}
          </h1>
            <!-- <hr class="mt-0 mb-4"> -->
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  <!-- Site footer -->
  <footer class="site-footer footer">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-6">
          <h6 class="footer-underline"><u>About</u></h6>
          <p class="text-justify">Web Pandas is a site created by Timothy Malahy. This was part pet project and part tool. It stemmed from a nuisance related to people at my workplace sending me messy and/or irregular data. It was also designed with the intention as being a proof of capabilities for potential employment.</p>
        </div>

        <div class="col-xs-6 col-md-3">
          <h6 class="footer-underline"><u>Quick Links</u></h6>
          <ul class="footer-links">
            <li><a href="">About Page</a></li>
            <li><a href="">Contact Me</a></li>
            <li><a href="">Contribute</a></li>
            <li><a href="">Privacy Policy</a></li>
            <li><a href="">Sitemap</a></li>
          </ul>
        </div>
        <div class="col-xs-6 col-md-3">
          <h6 class="footer-underline"><u>Social Links</u></h6>
          <div class="row">
            <div class="socialsColumn">
            <ul class="social-icons">
              <li>
                <a class="github" href="https://github.com/TimothyMalahy">
                  <span class="iconify" style="color:white;" data-icon="mdi:github">Git Hub</span>
                </a>
              </li>
              <li>
                <a class="linkedin" href="https://www.linkedin.com/in/timothy-malahy-766b62101">
                  <span class="iconify" style="color:white;" data-icon="mdi:linkedin"></span>
                </a>
              </li>   
              <li>
                <a class="twitter" href="https://twitter.com/TimPrograms">
                  <span class="iconify" style="color:white;" data-icon="mdi:twitter"></span>
                  <!-- <span class="svg-icon-bg iconBold"></span> -->
                </a>
              </li>
              <li>
                <a class="stackoverflow" href="https://stackoverflow.com/users/7370985/timothyjames67">
                  <span class="iconify" style="color:white;" data-icon="akar-icons:stack-overflow-fill"></span>
                </a>
              </li>  
            </ul>
          </div>
          </div>
        </div>
      </div>
      <hr>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-sm-6 col-xs-12">
          <p class="copyright-text">Copyright &copy; 2022 All Rights Reserved
          </p>
        </div>
      </div>
    </div>
</footer>
  </body>
</html>

<script>

</script>